#if !canImport(ObjectiveC)
import XCTest

extension APIotaCRUDRequestsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APIotaCRUDRequestsTests = [
        ("testDELETE", testDELETE),
        ("testDELETEPublisher", testDELETEPublisher),
        ("testGET", testGET),
        ("testGETPublisher", testGETPublisher),
        ("testPATCH", testPATCH),
        ("testPATCHPublisher", testPATCHPublisher),
        ("testPOST", testPOST),
        ("testPOSTPublisher", testPOSTPublisher),
        ("testPUT", testPUT),
        ("testPUTPublisher", testPUTPublisher),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(APIotaCRUDRequestsTests.__allTests__APIotaCRUDRequestsTests),
    ]
}
#endif
